version: '3'

services:
    frontend:
        build: ./frontend
        restart: always
        ports:
            - '3000:3000'
        volumes:
            # в первую очередь сохраняем папку node-modules
            #  которая в папке app
            - /app/node_modules
            # указываем относительный путь к папке
            # frontend (./) путь относительно ф-ла
            # docker-compose и куда мы ее монтируем в контейнере
            # в папку app
            - ./frontend:/app
    api:
        build: ./api
        restart: always
        ports:
            - '5555:5000'
            # Эти насторойки api и mysql (ниже)
            # важныдля того, чтобы запуск api
            # был произведен после запуска контейнера
            # mysql
        depends_on:
            mysql:
                condition: service_healthy
        volumes:
            # в первую очередь сохраняем папку node-modules
            #  которая в папке app
            - /app/node_modules
            # указываем относительный путь к папке
            # api (./) путь относительно ф-ла
            # docker-compose и куда мы ее монтируем в контейнере
            # - в папку app
            - ./api:/app
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_PORT: '3306'
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: time_db
    mysql:
        image: mysql
        restart: always
        # Настройка ниже перед запуском контейнера
        # каждые 20 секунд будет проверять,
        # запустилась ли база MySQL внутри контейнера mysql.
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            timeout: 20s
            retries: 10
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: time_db
            # Связь с томом сохраненных данных
        volumes:
            - mysql_data:/var/lib/mysql
    adminer:
        image: adminer
        restart: always
        ports:
            - '8888:8080'
# Подключение тома для сохранения данных при
# перезапуске контейнеров
volumes:
    mysql_data:
