version: '3'

services:
    frontend:
        build: ./frontend
        restart: always
        ports:
            - '3000:3000'
    api:
        build: ./api
        restart: always
        ports:
            - '5555:5000'
            # Эти насторойки api и mysql (ниже)
            # важныдля того, чтобы запуск api
            # был произведен после запуска контейнера
            # mysql
        depends_on:
            mysql:
                condition: service_healthy
    mysql:
        image: mysql
        restart: always
        # Настройка ниже перед запуском контейнера
        # каждые 20 секунд будет проверять,
        # запустилась ли база MySQL внутри контейнера mysql.
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            timeout: 20s
            retries: 10
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: time_db
    adminer:
        image: adminer
        restart: always
        ports:
            - '8888:8080'
